### 是否显示banner，可选值[true|false]
spring: 
       main: 
            banner-mode: CONSOLE
       profiles: 
                 active: dev
# REDIS (RedisProperties)
# Redis 数据索引(默认为0)
       redis:
             database: 1
# Redis服务器地址
             host: 114.55.132.207
#Redis服务器连接端口
             port: 6379
# Redis服务器连接密码（默认为空）
             password: kuyucoolfish888
# 连接超时时间 单位 ms（毫秒）
             timeout: 3000

#################redis线程池设置#################
# 连接池中的最大空闲连接，默认值也是8。
             pool: 
                  max-idle: 8
#连接池中的最小空闲连接，默认值也是0。
                  min-idle: 0
# 连接池最大连接数（使用负值表示没有限制）
# 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
                  max-active: 8
# 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
                  max-wait: -1
          
                    #日志系统 slfj logback
logging: 
        config: classpath:logback.xml
        path: D:/spring-boot/logs
        
httpclient: 
           config: 
                   # 代理的host 
                   proxyhost: xxx.xx.xx.xx  
                   # 代理端口  
                   proxyPort: 8080  
                   # 连接超时或异常重试次数  
                   retryTime: 3  
                   # 长连接保持时间，单位为s  
                   keepAliveTime: 30  
                   # 连接池最大连接数  
                   connMaxTotal: 20  
                   maxPerRoute: 20  
                   # 连接超时时间，单位ms  
                   connectTimeout: 2000  
                   # 请求超时时间  
                   connectRequestTimeout: 2000  
                   # sock超时时间  
                   socketTimeout: 2000  
                   # 连接存活时间，单位s  
                   timeToLive: 60  


---
#开发环境的配置
spring:
  profiles: dev
server:
  port: 8081
  
coolfish: 
         cmcc: 
              url: http://221.178.251.182:80/internet_surfing
              appid: 109000000114
              token: IWyDm4ie9o12WEmLJYm0
              groupid: 51810008262
              password: ZJWKJ3
              ddrcity: 15
              appid2: G12UC2VW  
              threadNumber: 12
               
---
#测试环境的配置
spring:
  profiles: test
server:
  port: 8082
coolfish: 
         cmcc: 
               url:  
               appid:  
               token:  

    
---
#生产环境的配置
spring:
  profiles: prd
server:
  port: 8083
        

