### 是否显示banner，可选值[true|false]
spring:
       main: 
            banner-mode: CONSOLE
       profiles: 
                 active: dev

#################配置rabbitmq的安装地址、端口以及账户信息#################
       rabbitmq: 
                 host: 114.55.132.207
                 port: 5672
                 username: coolfish
                 password: coolfish123
                 
                 
# REDIS (RedisProperties)
# Redis 数据索引(默认为0)
       redis:
             database: 1
# Redis服务器地址
             host: 114.55.132.207
#Redis服务器连接端口
             port: 6379
# Redis服务器连接密码（默认为空）
             password: kuyucoolfish888
# 连接超时时间 单位 ms（毫秒）
             timeout: 3000
#################redis线程池设置#################
# 连接池中的最大空闲连接，默认值也是8。
             pool: 
                  max-idle: 8
#连接池中的最小空闲连接，默认值也是0。
                  min-idle: 0
# 连接池最大连接数（使用负值表示没有限制）
# 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
                  max-active: 8
# 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
                  max-wait: -1
# 数据库访问配置
    # 主数据源，默认的
       datasource: 
                  type: com.alibaba.druid.pool.DruidDataSource
                 # url: jdbc:mysql://rm-wz9q2m8jgt8kr63d8.mysql.rds.aliyuncs.com/coolfish?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
                 # username: wapwei
                 # password: Wapwei123
                  url: jdbc:mysql://119.23.155.183:3307/coolfish?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
                  username: admin2
                  password: admin2
                 
                  driverClassName: com.mysql.jdbc.Driver
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
                  initialSize: 5
                  minIdle: 5
                  maxActive: 20
                  maxWait: 60000  # 配置获取连接等待超时的时间
                  timeBetweenEvictionRunsMillis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 
                  minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
                  validationQuery: SELECT 1 FROM DUAL
                  testWhileIdle: true
                  testOnBorrow: false
                  testOnReturn: false
     # 打开PSCache，并且指定每个连接上PSCache的大小 
                  poolPreparedStatements: true
                  maxPoolPreparedStatementPerConnectionSize: 20
                  filters: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 
                  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000   # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
                  useGlobalDataSourceStat: true   # 合并多个DruidDataSource的监控数据
 
    #JPA Configuration:  
       jpa: 
           database: MYSQL
    # Show or not log for each sql query
           show-sql: true
    #格式化sql
           properties: 
                      hibernate: 
                                format_sql: true
                                naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy 
                                dialect: org.hibernate.dialect.MySQL5Dialect  # 方言
    #实体类维护数据库表结构的具体行为：update/create/create-drop/validate/none
    #spring.jpa.hibernate.ddl-auto=create  

    ## 建表方式
           hibernate: 
                     ddl-auto: update
    #spring.jpa.properties.hibernate.hbm2ddl.auto=update 
    #spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect          
                    #日志系统 slfj logback
logging: 
        config: classpath:logback.xml
        path: java_logs/cmcc_tingji
        
httpclient: 
           config: 
                   # 代理的host 
                   proxyhost: xxx.xx.xx.xx  
                   # 代理端口  
                   proxyPort: 8080  
                   # 连接超时或异常重试次数  
                   retryTime: 3  
                   # 长连接保持时间，单位为s  
                   keepAliveTime: 30  
                   # 连接池最大连接数  
                   connMaxTotal: 20  
                   maxPerRoute: 20  
                   # 连接超时时间，单位ms  
                   connectTimeout: 2000  
                   # 请求超时时间  
                   connectRequestTimeout: 2000  
                   # sock超时时间  
                   socketTimeout: 2000  
                   # 连接存活时间，单位s  
                   timeToLive: 60  


---
#开发环境的配置
spring:
  profiles: dev
server:
  port: 8081
  
coolfish: 
         cmcc: 
              url: http://221.178.251.182:80/internet_surfing
              appid: 109000000114
              token: IWyDm4ie9o12WEmLJYm0
              groupid: 51810008262
              password: ZJWKJ3
              ddrcity: 15
              appid2: G12UC2VW  
              threadNumber: 12
              
         cha: 
             url: http://api.ct10649.com:9001/m2m_ec/query.do
             user_id: Szdsan2017
             password: Szdsan@2017
             keys: 23n3AHxkQ
         cotrol:
                remax: 6
                evmax: 3                   
---
#测试环境的配置
spring:
  profiles: test
server:
  port: 8082
coolfish: 
         cmcc: 
               url:  
               appid:  
               token:  

    
---
#生产环境的配置
spring:
  profiles: prd
server:
  port: 8083
        

